### ISSUE TITLE
Build Modelling Tab

### ISSUE THREAD

**Issue by hepaces89** [laurathepluralized/multi-agent-data-analysis#8]
Build the Modelling Tab

This tab will execute the modelling algorithm and display the results

Requires:

- [x] The modelling R code. Sorry I haven't gotten around to porting it over...

Context:
 - the data

Inputs:
- [x] List of X variables
- [x] the Y variable
- [x] the model type to run

Output:
- [x] The modelling results

- [ ] Get all model options to run correctly

**Comment by gtcooke94** [comment]
We currently output linear regression, but some of the other analyses error.
I've tried looking through, but since I didn't write these scripts I'm not really sure what is causing the problem.

**Comment by gtcooke94** [comment]
Got code ported in and have pushed a modeling tab to master.
It looks like multivariate linear regression works, but all of the others have some small issues when attempting to execute them. @kumbithwang could you take a look at this and see if you can fix the modeling.R file so that it runs?
Thanks!
Otherwise, we could just leave linear regression as the only fully fledged option for now.

**Comment by kumbithwang** [comment]
@gtcooke94 
Thanks for telling me the problem,
I will separate the code into part1: regression and part2: machine learning, and upload the code here again

**Comment by gtcooke94** [comment]
I'm using those files. I currently error out with
Error in predict: object 'lmtest2' not found

**Comment by gtcooke94** [comment]
Can you take a look at this and how it integrates into app.R? I'm not exactly sure what this backward selection is, but as far as I can tell, lmtest2 is never getting defined and it makes the whole shiny app crash. I don't know what it's supposed to be though, so I don't want to mess around with the actual regression that is happening.
